services:
  mysql:
    image: mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    command: npm run start:dev
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
